# Generated by Django 2.1.3 on 2019-03-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0002_auto_20190311_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='mtype',
            field=models.CharField(choices=[('XIGUA', '西瓜视频'), ('JIJI', '吉吉影音'), ('ONLINE', '在线播放')], default=1, max_length=100, verbose_name='播放方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='pmove',
            field=models.FileField(null=True, upload_to='media', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='resource',
            name='pname',
            field=models.CharField(max_length=255, null=True, verbose_name='分集地址'),
        ),
        migrations.AddField(
            model_name='resource',
            name='ptype',
            field=models.CharField(default=1, max_length=255, verbose_name='清晰程度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='purl',
            field=models.CharField(max_length=255, null=True, verbose_name='播放地址'),
        ),
    ]
