# Generated by Django 2.1.3 on 2019-03-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0003_auto_20190311_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerList',
        ),
    ]
