# Generated by Django 2.1.3 on 2019-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0004_delete_playerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('headImg', models.FileField(upload_to='media', verbose_name='文件')),
            ],
        ),
    ]
