# Generated by Django 2.1.3 on 2019-03-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0006_auto_20190311_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='area',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='pmove',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
