# Generated by Django 2.1.3 on 2019-03-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0008_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='area',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='pmov',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
